import { notFound } from "next/navigation";
import ChatPanel from "@/components/ChatPanel";
import DocumentCard from "@/components/DocumentCard";
import KnowledgeCard from "@/components/KnowledgeCard";
import SectionTitle from "@/components/SectionTitle";
import TagBadge from "@/components/TagBadge";
import ToolCard from "@/components/ToolCard";
import WorkerCapability from "@/components/WorkerCapability";
import WorkflowCard from "@/components/WorkflowCard";
import { getAllDocuments } from "@/data/documents";
import { getAllWorkers } from "@/data/workers";
import { getRetrievalReadyDocumentIds } from "@/lib/services/knowledge/knowledgeHubBridge";
import { WorkforceService } from "@/services/workforce/WorkforceService";

// The Overview page answers exactly one question: "What is this digital
// employee?" — responsibilities, business value, success measure, and what
// it's connected to. Daily work lives on Workspace; reasoning internals
// live on Intelligence (see the sibling page.tsx files in this segment).
export function generateStaticParams() {
  return getAllWorkers().map((worker) => ({ slug: worker.slug }));
}

export default async function WorkerOverviewPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const workerInstance = WorkforceService.getById(slug);

  if (!workerInstance) {
    notFound();
  }

  const worker = WorkforceService.toCardData(workerInstance);
  const availableActions = workerInstance.definition.availableActions;
  const availableDocuments = getAllDocuments().filter((document) => document.usedBy.includes(worker.name));
  const connectedDepartments = Array.from(
    new Set([worker.department, ...availableDocuments.map((document) => document.department)]),
  );
  const retrievalReadyIds = await getRetrievalReadyDocumentIds();
  const retrievalReadyCount = availableDocuments.filter((document) =>
    retrievalReadyIds.has(document.id),
  ).length;

  return (
    <>
      <section>
        <SectionTitle title="Purpose" />
        <p className="text-slate-300">{worker.purpose}</p>
      </section>

      <section>
        <SectionTitle
          title="Responsibilities"
          description="Concrete actions this worker's Decision stage can take, generated by the Digital Workforce Engine."
        />
        {availableActions.length === 0 ? (
          <p className="text-sm text-slate-500">No actions registered for this worker yet.</p>
        ) : (
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            {availableActions.map((action) => (
              <WorkflowCard key={action.id} name={action.name} description={action.description} />
            ))}
          </div>
        )}
      </section>

      <section>
        <SectionTitle
          title="How Success Is Measured"
          description="What this worker is judged by — not a live reading (see Intelligence for current health), a definition of what matters."
        />
        <div className="rounded-xl bg-slate-900 p-6">
          <p className="text-sm text-slate-200">{worker.successMetric}</p>
        </div>
      </section>

      <section>
        <SectionTitle
          title="Available Knowledge"
          description="Company knowledge this worker draws on when answering questions or making decisions."
        />
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">
          {worker.knowledgeSources.map((source) => (
            <KnowledgeCard key={source} name={source} />
          ))}
        </div>

        <div className="mt-6 flex flex-wrap items-center gap-4">
          <div className="flex flex-wrap gap-2">
            {connectedDepartments.map((department) => (
              <TagBadge key={department} label={department} />
            ))}
          </div>
          <span className="text-sm text-slate-400">
            {retrievalReadyCount} of {availableDocuments.length} documents retrieval-ready
          </span>
        </div>

        {availableDocuments.length === 0 ? (
          <p className="mt-4 text-sm text-slate-500">No Knowledge Hub document is linked yet.</p>
        ) : (
          <div className="mt-4 grid grid-cols-1 gap-5 md:grid-cols-2">
            {availableDocuments.map((document) => (
              <DocumentCard key={document.id} document={document} />
            ))}
          </div>
        )}
      </section>

      <section>
        <SectionTitle
          title="Connected Workflows"
          description="Workflow Automation this worker can trigger from a decision."
        />
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          {worker.workflows.map((workflow) => (
            <WorkflowCard
              key={workflow.name}
              name={workflow.name}
              description={workflow.description}
            />
          ))}
        </div>
      </section>

      <section>
        <SectionTitle
          title="Connected Systems"
          description="Enterprise Integrations this worker can act through."
        />
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">
          {worker.tools.map((tool) => (
            <ToolCard key={tool} name={tool} />
          ))}
        </div>
      </section>

      <section>
        <SectionTitle title="Current Capabilities" />
        <WorkerCapability worker={worker} />
      </section>

      <section>
        <SectionTitle
          title="Worker Chat"
          description={`Ask the ${worker.name} about its role, responsibilities, or what it can help with.`}
        />
        <ChatPanel
          aiLabel={worker.name}
          placeholder={`Ask the ${worker.name}...`}
          initialMessages={[
            {
              role: "ai",
              content: `Hi, I'm the ${worker.name}. ${worker.purpose}`,
            },
          ]}
        />
      </section>
    </>
  );
}
