import type { Industry } from "@/lib/enterprise/EnterpriseTypes";

export interface IndustryTemplate {
  industry: Industry;
  companyNames: string[];
  taglines: string[];
  hqCities: { city: string; region: string }[];
  productNamePool: string[];
  productCategories: string[];
  customerNamePool: string[];
  customerSegments: string[];
  supplierNamePool: string[];
  supplierCategories: string[];
  employeeDepartments: { department: string; titles: string[] }[];
  riskScenarios: string[];
  opportunityScenarios: string[];
  milestoneScenarios: string[];
  operationalScenarios: string[];
  campaignChannels: string[];
  ticketSubjects: string[];
  documentTitles: string[];
  documentDescriptions: string[];
  unitLabel: string;
  tracksInventory: boolean;
  facilityLabel: string;
}

// 20 titles/descriptions per industry, index-matched to DOC_ROLES in
// DocumentContentBuilder.ts (first 12/16/20 used depending on company
// size). Order: employee-handbook, onboarding-sop, leave-policy,
// financial-report, invoice-register, sales-playbook, pipeline-report,
// warehouse-sop, inventory-master, vendor-msa, compliance-checklist,
// admin-travel-policy, support-macros, product-faq, brand-guidelines,
// network-architecture, board-report, meeting-minutes, training-manual,
// product-catalogue.

export const INDUSTRY_TEMPLATES: Record<Industry, IndustryTemplate> = {
  Agriculture: {
    industry: "Agriculture",
    tracksInventory: true,
    facilityLabel: "Storage Facility",
    companyNames: ["Terra Harvest Sdn Bhd", "Ganesh Agro Ventures", "Emerald Fields Agribusiness", "Sawit Prima Holdings", "Kebun Jaya Agri Group"],
    taglines: [
      "Feeding the region, one harvest at a time.",
      "From soil to shelf, engineered for yield.",
      "Sustainable agriculture at commercial scale.",
      "Precision farming for a growing market.",
    ],
    hqCities: [
      { city: "Johor Bahru", region: "Johor" },
      { city: "Kota Kinabalu", region: "Sabah" },
      { city: "Kuching", region: "Sarawak" },
      { city: "Ipoh", region: "Perak" },
    ],
    productNamePool: ["Premium Palm Oil (CPO)", "Highland Robusta Coffee Beans", "Organic Jasmine Rice", "Fresh Cavendish Bananas", "Cold-Pressed Coconut Oil", "Durian Musang King (Frozen)", "Free-Range Chicken Eggs", "Hydroponic Lettuce", "Dried Black Pepper", "Natural Rubber Sheets", "Fertilizer Blend NPK-15", "Pineapple Concentrate"],
    productCategories: ["Plantation Crops", "Livestock & Poultry", "Processed Produce", "Agri-Inputs"],
    customerNamePool: ["Golden Harvest Distributors", "PantryFresh Wholesale", "Nusantara Food Exports", "AgriMart Retail Group", "Coastal Grain Traders", "Highland Beverage Co.", "FreshLine Supermarkets", "EastAsia Commodities", "GreenPlate Foodservice", "Borneo Export Alliance", "Metro Wet Market Federation", "PureHarvest Co-operative"],
    customerSegments: ["Export Distributor", "Wholesale Buyer", "Retail Chain", "Foodservice"],
    supplierNamePool: ["AgriChem Supplies Sdn Bhd", "Borneo Seed & Fertilizer Co.", "Highland Equipment Rentals", "IrrigateTech Solutions", "PackFresh Cold Chain", "Tractor Works Malaysia", "GreenGrow Agri-Inputs"],
    supplierCategories: ["Seeds & Fertilizer", "Farm Equipment", "Cold Chain Logistics", "Crop Protection"],
    employeeDepartments: [
      { department: "Plantation Operations", titles: ["Plantation Manager", "Field Supervisor", "Harvest Coordinator", "Agronomist"] },
      { department: "Quality & Compliance", titles: ["Quality Control Officer", "Sustainability Auditor", "Food Safety Manager"] },
      { department: "Sales & Export", titles: ["Export Sales Manager", "Key Account Executive", "Trade Documentation Officer"] },
      { department: "Finance", titles: ["Finance Manager", "Accounts Executive", "Credit Controller"] },
      { department: "Supply Chain", titles: ["Logistics Manager", "Warehouse Supervisor", "Procurement Officer"] },
    ],
    riskScenarios: [
      "Prolonged dry spell forecast to reduce next quarter's yield on {product}",
      "Fertilizer input costs up sharply, compressing margins on {product}",
      "Key export buyer {customer} delaying payment on a large shipment",
      "Pest outbreak reported at one plantation block affecting {product}",
      "Shipping container shortage delaying export of {product} to {customer}",
    ],
    opportunityScenarios: [
      "Spot market price for {product} up on regional supply shortage",
      "New export certification opens EU market access for {product}",
      "{customer} requesting a long-term supply contract for {product}",
    ],
    milestoneScenarios: [
      "Completed harvest cycle for {product} ahead of schedule",
      "Passed annual sustainability certification audit",
      "Onboarded {customer} as a new export partner",
    ],
    operationalScenarios: [
      "Irrigation system upgrade completed at the main plantation block",
      "New cold storage facility brought online",
      "Harvest labor roster finalized for peak season",
    ],
    campaignChannels: ["Trade Shows", "Export Trade Missions", "Digital Marketplace Listings", "Cooperative Bulletins"],
    ticketSubjects: ["Delayed shipment inquiry", "Quality complaint on delivered batch", "Certificate of origin request", "Pricing renegotiation request"],
    documentTitles: [
      "Estate Worker Handbook 2026", "Field Staff Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 Harvest & Financial Report", "Outstanding Buyer Invoice Register", "Export Sales Playbook",
      "Monthly Export Pipeline Report", "Plantation & Warehouse Operations SOP", "Crop Inventory Master List",
      "Supplier Master Service Agreement", "Agricultural Compliance Checklist", "Field Travel & Expense Policy",
      "Buyer Support Response Guide", "Product & Harvest FAQ Knowledge Base", "Brand & Export Guidelines",
      "Farm IT & Sensor Network Overview", "Board Report — Harvest Performance", "Estate Management Meeting Minutes",
      "New Agronomist Training Manual", "Produce Catalogue 2026",
    ],
    documentDescriptions: [
      "Company-wide policies covering estate conduct, safety, and worker welfare.",
      "Step-by-step onboarding checklist for new field and estate staff.",
      "Annual leave entitlement, attendance tracking, and approval workflow for estate staff.",
      "Consolidated harvest volumes, revenue, and cash flow for the quarter.",
      "Live register of issued export invoices and their payment status.",
      "Export sales process, pricing bands, and buyer negotiation guidance.",
      "Snapshot of open export deals by stage and destination market.",
      "Standard procedures for harvesting, storage, and dispatch across plantation blocks.",
      "Current crop stock levels, reorder points, and buyer allocations by product.",
      "Standard contract terms for approved input suppliers and equipment vendors.",
      "Checklist of agricultural and export regulatory obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for field travel.",
      "Approved response templates and escalation criteria for buyer queries.",
      "Frequently asked buyer questions and approved answers by product line.",
      "Visual identity and export marketing guidelines.",
      "Current farm sensor and IT network topology and access control map.",
      "Quarterly board briefing on harvest performance and export pipeline.",
      "Minutes from the monthly estate management review meeting.",
      "Onboarding and safety training manual for new agronomists.",
      "Current season's produce catalogue with specifications and grading.",
    ],
    unitLabel: "tonnes",
  },

  Manufacturing: {
    industry: "Manufacturing",
    tracksInventory: true,
    facilityLabel: "Distribution Center",
    companyNames: ["Prima Steel Works Sdn Bhd", "Nexus Industrial Manufacturing", "IronForge Precision Sdn Bhd", "Delta Components Group", "Apex Fabrication Industries"],
    taglines: [
      "Precision engineering, delivered on schedule.",
      "Built to spec, shipped on time, every time.",
      "Manufacturing excellence at industrial scale.",
      "From raw material to finished part, under one roof.",
    ],
    hqCities: [
      { city: "Shah Alam", region: "Selangor" },
      { city: "Johor Bahru", region: "Johor" },
      { city: "Penang", region: "Penang" },
      { city: "Klang", region: "Selangor" },
    ],
    productNamePool: ["Precision Steel Bracket Assembly", "Injection-Molded Housing Unit", "CNC-Machined Shaft Component", "Industrial Gearbox Model GX-40", "Aluminum Extrusion Profile", "Sheet Metal Enclosure", "Hydraulic Cylinder Assembly", "Powder-Coated Panel Set", "Custom PCB Enclosure", "Rubber Gasket Seal Kit", "Forged Flange Coupling", "Automated Conveyor Module"],
    productCategories: ["Precision Components", "Assemblies", "Tooling & Fixtures", "Finished Sub-Systems"],
    customerNamePool: ["Meridian Auto Parts", "Continental Machinery Group", "TitanBuild Industrial", "Northgate Electronics", "Summit Equipment Manufacturing", "Vantage Aerospace Components", "Reliance Heavy Industries", "Pinnacle OEM Solutions", "Orion Assembly Systems", "Cascade Engineering Group", "BlueRidge Manufacturing Co.", "Consolidated Fabricators Ltd."],
    customerSegments: ["OEM Partner", "Tier 1 Supplier", "Distributor", "Direct Industrial"],
    supplierNamePool: ["SteelSource Raw Materials", "PolyGrade Plastics Sdn Bhd", "PrecisionTool Machining Co.", "MetalWorks Coating Services", "IndustrialBolt Fasteners", "AlloyTech Casting Supply", "ElectroComponents Trading"],
    supplierCategories: ["Raw Materials", "Machining Services", "Surface Finishing", "Fasteners & Hardware"],
    employeeDepartments: [
      { department: "Production", titles: ["Production Manager", "Line Supervisor", "Machine Operator", "Process Engineer"] },
      { department: "Quality Assurance", titles: ["QA Manager", "Quality Inspector", "Six Sigma Analyst"] },
      { department: "Sales", titles: ["Sales Manager", "Account Executive", "Sales Coordinator"] },
      { department: "Finance", titles: ["Finance Manager", "Cost Accountant", "Accounts Receivable Clerk"] },
      { department: "Supply Chain", titles: ["Supply Chain Manager", "Procurement Officer", "Warehouse Supervisor"] },
    ],
    riskScenarios: [
      "CNC machine downtime on Line 2 affecting {product} output",
      "Raw material cost increase from {supplier} squeezing margins",
      "Quality defect rate above threshold on {product}",
      "{customer} invoice 45+ days overdue",
      "Key supplier {supplier} reporting a lead-time delay",
    ],
    opportunityScenarios: [
      "{customer} requesting a volume increase on {product}",
      "New certification opens defense-sector contracts",
      "Automation upgrade projected to cut {product} unit cost",
    ],
    milestoneScenarios: [
      "Shipped largest single order of {product} to date",
      "Passed ISO 9001 surveillance audit with zero non-conformances",
      "Commissioned new production line for {product}",
    ],
    operationalScenarios: [
      "Preventive maintenance completed across Line 1 and Line 2",
      "New quality inspection station deployed on the factory floor",
      "Shift schedule optimized for peak-season throughput",
    ],
    campaignChannels: ["Trade Shows", "Industry Publications", "Direct OEM Outreach", "LinkedIn"],
    ticketSubjects: ["Defect report on delivered batch", "Delivery schedule inquiry", "Technical spec clarification", "Warranty claim"],
    documentTitles: [
      "Factory Worker Handbook 2026", "Production Staff Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 Manufacturing Financial Report", "Outstanding Customer Invoice Register", "OEM Sales Playbook",
      "Monthly Order Pipeline Report", "Factory Floor Operations SOP", "Finished Goods Inventory Master List",
      "Supplier Master Service Agreement", "ISO Compliance Checklist", "Corporate Travel & Expense Policy",
      "Customer Support Response Guide", "Product Spec FAQ Knowledge Base", "Brand & Marketing Guidelines",
      "Factory Network & OT Architecture Overview", "Board Report — Production Performance", "Operations Review Meeting Minutes",
      "New Machine Operator Training Manual", "Product Catalogue 2026",
    ],
    documentDescriptions: [
      "Company-wide policies covering factory conduct, safety, and workplace standards.",
      "Step-by-step onboarding checklist for new production staff.",
      "Annual leave entitlement, attendance tracking, and approval workflow.",
      "Consolidated production output, revenue, and cash flow for the quarter.",
      "Live register of issued customer invoices and their payment status.",
      "OEM sales process, quoting guidance, and account management playbook.",
      "Snapshot of open orders by stage and customer.",
      "Standard procedures for production, quality hold, and dispatch on the factory floor.",
      "Current finished-goods stock levels, reorder points, and customer allocations.",
      "Standard contract terms for approved raw material and machining suppliers.",
      "Checklist of ISO and regulatory obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for business travel.",
      "Approved response templates and escalation criteria for customer complaints.",
      "Frequently asked customer questions on specifications, by product line.",
      "Visual identity, tone of voice, and trade show guidelines.",
      "Current factory network and operational-technology topology and access map.",
      "Quarterly board briefing on production performance and order pipeline.",
      "Minutes from the monthly operations review meeting.",
      "Onboarding and safety training manual for new machine operators.",
      "Current product line catalogue with specifications and lead times.",
    ],
    unitLabel: "units",
  },

  Healthcare: {
    industry: "Healthcare",
    tracksInventory: false,
    facilityLabel: "Clinic Branch",
    companyNames: ["MedCare Specialist Group", "Sentosa Health Partners", "Wellspring Medical Centre Group", "Harmony Healthcare Sdn Bhd", "Pulse Diagnostics & Care"],
    taglines: [
      "Patient-centered care, backed by data.",
      "Accessible specialist care across the region.",
      "Modern healthcare, delivered with compassion.",
      "Diagnostics and care under one trusted roof.",
    ],
    hqCities: [
      { city: "Kuala Lumpur", region: "Federal Territory" },
      { city: "Penang", region: "Penang" },
      { city: "Petaling Jaya", region: "Selangor" },
      { city: "Kuching", region: "Sarawak" },
    ],
    productNamePool: ["General Health Screening Package", "Cardiology Consultation Package", "Physiotherapy Session Bundle", "Diagnostic Imaging (MRI) Package", "Maternity Care Package", "Dental Care Package", "Vaccination Programme", "Chronic Disease Management Plan", "Home Nursing Service", "Executive Health Screening", "Laboratory Test Panel", "Telehealth Consultation Package"],
    productCategories: ["Consultation Services", "Diagnostic Services", "Wellness Programmes", "Home Care"],
    customerNamePool: ["Sunrise Corporate Wellness", "MediPlan Insurance Group", "Harbor Point Panel Clinic Network", "TechCorp Employee Health Programme", "Golden Years Retirement Community", "Family First HMO", "Regional Hospital Referral Network", "CorpCare Employee Benefits", "WellLife Insurance Partners", "Metro Panel Doctor Network", "Bright Future School District", "National Sports Council"],
    customerSegments: ["Corporate Client", "Insurance Panel", "Referral Network", "Individual Patient"],
    supplierNamePool: ["MedSupply Distribution Sdn Bhd", "PharmaLink Wholesale", "DiagnosticTech Equipment Co.", "SteriCare Hygiene Supplies", "LabEquip Solutions", "MediGas & Consumables", "HealthIT Systems Provider"],
    supplierCategories: ["Pharmaceuticals", "Medical Equipment", "Consumables & PPE", "Health IT Systems"],
    employeeDepartments: [
      { department: "Clinical Operations", titles: ["Chief Medical Officer", "Consultant Physician", "Nurse Manager", "Clinical Coordinator"] },
      { department: "Patient Services", titles: ["Patient Services Manager", "Front Desk Coordinator", "Patient Advocate"] },
      { department: "Finance", titles: ["Finance Manager", "Billing Executive", "Insurance Claims Officer"] },
      { department: "Quality & Compliance", titles: ["Quality Manager", "Compliance Officer", "Infection Control Nurse"] },
      { department: "Operations", titles: ["Facilities Manager", "Supply Officer", "IT Systems Administrator"] },
    ],
    riskScenarios: [
      "Nurse staffing shortfall in the {product} unit next week",
      "{customer} insurance claim backlog growing past 30 days",
      "Medical consumable stock for {product} running low",
      "Patient wait times for {product} above target",
      "Upcoming accreditation audit requires policy gap closure",
    ],
    opportunityScenarios: [
      "{customer} requesting an expanded corporate wellness contract",
      "New telehealth demand opening a same-day consultation offering",
      "Panel clinic network proposing a bundled {product} package",
    ],
    milestoneScenarios: [
      "Completed 1,000th {product} this quarter",
      "Passed hospital accreditation renewal audit",
      "Onboarded {customer} as a new corporate panel client",
    ],
    operationalScenarios: [
      "New patient scheduling system rolled out clinic-wide",
      "Diagnostic equipment calibration completed",
      "Staff roster rebalanced to reduce wait times",
    ],
    campaignChannels: ["Corporate Wellness Fairs", "Insurance Panel Outreach", "Community Health Talks", "Digital Health Content"],
    ticketSubjects: ["Appointment rescheduling request", "Billing/insurance claim dispute", "Test result inquiry", "Service complaint"],
    documentTitles: [
      "Clinical Staff Handbook 2026", "New Clinician Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 Clinic Financial Report", "Outstanding Insurance Claims Register", "Corporate Wellness Sales Playbook",
      "Monthly Patient Referral Pipeline Report", "Clinical Operations SOP", "Medical Consumables Inventory Master List",
      "Supplier Master Service Agreement", "Healthcare Compliance Checklist", "Staff Travel & Expense Policy",
      "Patient Support Response Guide", "Patient FAQ Knowledge Base", "Brand & Patient Communications Guidelines",
      "Clinical IT & Records Network Overview", "Board Report — Clinical Performance", "Medical Board Meeting Minutes",
      "New Nurse Training Manual", "Service & Package Catalogue 2026",
    ],
    documentDescriptions: [
      "Company-wide policies covering clinical conduct, patient safety, and workplace standards.",
      "Step-by-step onboarding checklist for new clinical staff.",
      "Annual leave entitlement, attendance tracking, and approval workflow.",
      "Consolidated patient volumes, revenue, and cash flow for the quarter.",
      "Live register of submitted insurance claims and their reimbursement status.",
      "Corporate wellness sales process and account management playbook.",
      "Snapshot of open referral and panel discussions by stage.",
      "Standard procedures for patient intake, triage, and clinical handoff.",
      "Current medical consumable and equipment stock levels and reorder points.",
      "Standard contract terms for approved pharmaceutical and equipment suppliers.",
      "Checklist of healthcare regulatory and accreditation obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for staff travel.",
      "Approved response templates and escalation criteria for patient queries.",
      "Frequently asked patient questions and approved answers by service line.",
      "Visual identity and patient communications guidelines.",
      "Current clinical IT and patient records network topology and access map.",
      "Quarterly board briefing on clinical performance and referral pipeline.",
      "Minutes from the monthly medical board review meeting.",
      "Onboarding and clinical training manual for new nurses.",
      "Current service and package catalogue with pricing.",
    ],
    unitLabel: "cases",
  },

  Retail: {
    industry: "Retail",
    tracksInventory: true,
    facilityLabel: "Distribution Center",
    companyNames: ["Ganick Distribution Sdn Bhd", "Metro Mart Retail Group", "Nova Lifestyle Retail", "Sentral Trading Sdn Bhd", "BrightStore Retail Holdings"],
    taglines: [
      "Everyday essentials, delivered reliably.",
      "Retail that knows what its customers want next.",
      "From distribution to shelf, one connected network.",
      "Local reach, national scale.",
    ],
    hqCities: [
      { city: "Kuala Lumpur", region: "Federal Territory" },
      { city: "Petaling Jaya", region: "Selangor" },
      { city: "Johor Bahru", region: "Johor" },
      { city: "Penang", region: "Penang" },
    ],
    productNamePool: ["Ganick Ginger Beverage 330ml", "Premium Instant Noodles Pack", "Household Cleaning Bundle", "Everyday Rice 5kg", "Cooking Oil 2L", "Snack Variety Box", "Personal Care Bundle", "Frozen Ready Meals Pack", "Bottled Mineral Water Case", "Breakfast Cereal Family Pack", "Laundry Detergent 3kg", "Canned Goods Assortment"],
    productCategories: ["Beverages", "Packaged Food", "Household Goods", "Personal Care"],
    customerNamePool: ["ABC Distributor", "FreshMart Supermarkets", "Metro Convenience Chain", "ValueSave Hypermarket", "Corner Store Cooperative", "QuickShop Retail Group", "Family Grocer Network", "PriceWise Wholesale Club", "Neighbourhood Mart Alliance", "SuperSave Retail Chain", "Urban Pantry Stores", "Daily Needs Distributors"],
    customerSegments: ["Distributor", "Hypermarket Chain", "Convenience Chain", "Independent Retailer"],
    supplierNamePool: ["PackRight Packaging Supplies", "FreshChain Cold Logistics", "IngredientSource Trading", "BottleWorks Manufacturing", "LabelPro Printing Services", "PalletTrans Logistics", "RawGoods Import Sdn Bhd"],
    supplierCategories: ["Raw Ingredients", "Packaging", "Cold Chain Logistics", "Printing & Labeling"],
    employeeDepartments: [
      { department: "Sales & Distribution", titles: ["Sales Manager", "Territory Sales Executive", "Key Account Manager"] },
      { department: "Warehouse", titles: ["Warehouse Manager", "Inventory Controller", "Forklift Operator"] },
      { department: "Finance", titles: ["Finance Manager", "Credit Controller", "Accounts Executive"] },
      { department: "Marketing", titles: ["Marketing Manager", "Brand Executive", "Trade Marketing Executive"] },
      { department: "Customer Service", titles: ["Customer Service Manager", "Support Executive"] },
    ],
    riskScenarios: [
      "{product} inventory at the main warehouse running critically low",
      "{customer} has not reordered {product} in over 27 days",
      "{customer} invoice significantly overdue",
      "Packaging supplier {supplier} reporting a delay",
      "Shelf-life risk building on slow-moving {product} stock",
    ],
    opportunityScenarios: [
      "{customer} requesting a larger standing order for {product}",
      "Seasonal demand spike expected for {product}",
      "New convenience chain {customer} open to a distribution agreement",
    ],
    milestoneScenarios: [
      "Reached record monthly sell-through on {product}",
      "Onboarded {customer} as a new distribution partner",
      "Completed warehouse re-layout improving pick times",
    ],
    operationalScenarios: [
      "Delivery route optimization completed for the northern region",
      "New point-of-sale system rolled out across partner stores",
      "Warehouse cycle count completed with no major discrepancies",
    ],
    campaignChannels: ["In-Store Promotions", "Social Media", "Trade Marketing", "Email"],
    ticketSubjects: ["Delivery delay inquiry", "Damaged goods complaint", "Reorder request", "Pricing dispute"],
    documentTitles: [
      "Employee Handbook 2026", "Employee Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 Financial Report", "Outstanding Invoice Register", "Enterprise Sales Playbook",
      "Monthly Pipeline Report", "Warehouse Operations SOP", "Inventory Master List",
      "Vendor Master Service Agreement", "Regulatory Compliance Checklist", "Corporate Travel & Expense Policy",
      "Customer Support Response Guide", "Product FAQ Knowledge Base", "Brand & Marketing Guidelines",
      "IT Network Architecture Overview", "Board Report — Retail Performance", "Trade Marketing Meeting Minutes",
      "New Sales Rep Training Manual", "Product Catalogue 2026",
    ],
    documentDescriptions: [
      "Company-wide policies covering conduct, benefits, and workplace standards.",
      "Step-by-step onboarding checklist for new hires across departments.",
      "Annual leave entitlement, attendance tracking, and approval workflow.",
      "Consolidated revenue, expenses, and cash flow for the quarter.",
      "Live register of issued invoices and their payment status.",
      "Sales process, objection handling, and pricing guidance for distribution deals.",
      "Snapshot of open opportunities by stage and owner.",
      "Standard procedures for receiving, storing, and dispatching inventory.",
      "Current stock levels, reorder points, and supplier references by SKU.",
      "Standard contract terms for approved suppliers and vendors.",
      "Checklist of regulatory obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for business travel.",
      "Approved response templates and escalation criteria for support tickets.",
      "Frequently asked customer questions and approved answers by product line.",
      "Visual identity, tone of voice, and campaign approval process.",
      "Current network topology, system ownership, and access control map.",
      "Quarterly board briefing on retail performance and distribution pipeline.",
      "Minutes from the monthly trade marketing review meeting.",
      "Onboarding and product training manual for new sales representatives.",
      "Current product catalogue with pricing and case-pack details.",
    ],
    unitLabel: "cases",
  },

  "Beauty & Wellness": {
    industry: "Beauty & Wellness",
    tracksInventory: false,
    facilityLabel: "Studio Location",
    companyNames: ["Lumière Beauty Group", "Serene Wellness Sdn Bhd", "PureGlow Spa & Aesthetics", "Radiance Beauty Collective", "Zenith Wellness Studio Group"],
    taglines: [
      "Where self-care meets science.",
      "Beauty and wellness, personalized.",
      "Feel renewed, look radiant.",
      "Premium care for everyday wellness.",
    ],
    hqCities: [
      { city: "Kuala Lumpur", region: "Federal Territory" },
      { city: "Petaling Jaya", region: "Selangor" },
      { city: "Penang", region: "Penang" },
      { city: "Johor Bahru", region: "Johor" },
    ],
    productNamePool: ["Signature Facial Treatment", "Deep Tissue Massage Package", "Hydrating Skincare Bundle", "Hair Spa & Treatment Package", "Body Contouring Session", "Bridal Beauty Package", "Aromatherapy Wellness Session", "Anti-Aging Serum Collection", "Nail Care Package", "Detox Wellness Retreat Package", "Men's Grooming Package", "Membership Wellness Plan",
    ],
    productCategories: ["Skincare Services", "Spa & Massage", "Retail Products", "Membership Programmes"],
    customerNamePool: ["Radiant Hotels Spa Partnership", "GlowUp Retail Distribution", "Wellness Corporate Perks Programme", "Bridal Concierge Network", "Luxe Mall Beauty Counter", "CityLife Members Club", "Serenity Resort Group", "PamperMe Gifting Partners", "TrendSpa Franchise Network", "HealthFirst Employee Benefits", "SkinCare Retail Alliance", "Urban Spa Collective",
    ],
    customerSegments: ["Membership Client", "Corporate Wellness Partner", "Retail Partner", "Walk-In Client"],
    supplierNamePool: ["PureIngredients Cosmetics Supply", "SpaEquip Trading Sdn Bhd", "AromaSource Essential Oils", "BeautyPack Packaging Co.", "SkinLab Formulation Partners", "WellnessTech Equipment", "OrganicBase Ingredients"],
    supplierCategories: ["Cosmetic Ingredients", "Spa Equipment", "Packaging", "Formulation Partners"],
    employeeDepartments: [
      { department: "Studio Operations", titles: ["Spa Manager", "Senior Therapist", "Aesthetician", "Studio Coordinator"] },
      { department: "Client Services", titles: ["Client Relations Manager", "Front Desk Executive", "Membership Coordinator"] },
      { department: "Finance", titles: ["Finance Manager", "Billing Executive"] },
      { department: "Marketing", titles: ["Marketing Manager", "Content Creator", "Influencer Partnerships Executive"] },
      { department: "Product & Retail", titles: ["Retail Manager", "Inventory Coordinator"] },
    ],
    riskScenarios: [
      "{product} appointment no-show rate rising this month",
      "Booking capacity for {product} fully booked ahead of a promotion",
      "{customer} membership renewal at risk of lapsing",
      "Key ingredient supplier {supplier} reporting a delay",
      "Therapist scheduling gap during peak weekend hours",
    ],
    opportunityScenarios: [
      "{customer} requesting a bulk corporate wellness package",
      "New {product} launch generating strong pre-booking interest",
      "Influencer campaign driving a spike in new client inquiries",
    ],
    milestoneScenarios: [
      "Reached record monthly bookings for {product}",
      "Opened a new studio location",
      "Onboarded {customer} as a new corporate wellness partner",
    ],
    operationalScenarios: [
      "New online booking system rolled out across studios",
      "Staff training completed on the latest treatment protocol",
      "Retail shelf reset completed ahead of the new season",
    ],
    campaignChannels: ["Instagram & Social Media", "Influencer Partnerships", "Email", "In-Studio Promotions"],
    ticketSubjects: ["Booking reschedule request", "Treatment reaction complaint", "Membership billing inquiry", "Product return request"],
    documentTitles: [
      "Staff Handbook 2026", "Therapist Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 Studio Financial Report", "Outstanding Membership Invoice Register", "Corporate Wellness Sales Playbook",
      "Monthly Booking Pipeline Report", "Studio Operations SOP", "Retail & Treatment Inventory Master List",
      "Supplier Master Service Agreement", "Health & Safety Compliance Checklist", "Staff Travel & Expense Policy",
      "Client Support Response Guide", "Treatment FAQ Knowledge Base", "Brand & Content Guidelines",
      "Studio IT & Booking System Overview", "Board Report — Studio Performance", "Studio Leadership Meeting Minutes",
      "New Therapist Training Manual", "Treatment & Retail Catalogue 2026",
    ],
    documentDescriptions: [
      "Company-wide policies covering studio conduct, hygiene, and workplace standards.",
      "Step-by-step onboarding checklist for new therapists and aestheticians.",
      "Annual leave entitlement, attendance tracking, and approval workflow.",
      "Consolidated bookings, revenue, and cash flow for the quarter.",
      "Live register of issued membership invoices and their payment status.",
      "Corporate wellness sales process and account management playbook.",
      "Snapshot of open bookings and partnership discussions by stage.",
      "Standard procedures for treatment room turnover, hygiene, and client flow.",
      "Current retail and treatment consumable stock levels and reorder points.",
      "Standard contract terms for approved ingredient and equipment suppliers.",
      "Checklist of health, safety, and licensing obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for staff travel.",
      "Approved response templates and escalation criteria for client complaints.",
      "Frequently asked client questions and approved answers by treatment line.",
      "Visual identity, tone of voice, and content approval process.",
      "Current studio IT and booking system topology and access map.",
      "Quarterly board briefing on studio performance and booking pipeline.",
      "Minutes from the monthly studio leadership review meeting.",
      "Onboarding and treatment training manual for new therapists.",
      "Current treatment and retail product catalogue with pricing.",
    ],
    unitLabel: "sessions",
  },

  Logistics: {
    industry: "Logistics",
    tracksInventory: true,
    facilityLabel: "Distribution Hub",
    companyNames: ["Selat Logistics Group", "SwiftFreight Sdn Bhd", "Pantas Cargo & Distribution", "Meridian Supply Chain Solutions", "Harbourlink Freight Services"],
    taglines: [
      "Freight moved on time, every time.",
      "Connecting the region's supply chains.",
      "From port to doorstep, fully tracked.",
      "Logistics built for scale.",
    ],
    hqCities: [
      { city: "Port Klang", region: "Selangor" },
      { city: "Penang", region: "Penang" },
      { city: "Johor Bahru", region: "Johor" },
      { city: "Kuantan", region: "Pahang" },
    ],
    productNamePool: ["Full Truckload (FTL) Service", "Less-Than-Truckload (LTL) Service", "Warehousing & Fulfillment Package", "Last-Mile Delivery Service", "Cold Chain Transport Service", "Freight Forwarding (Sea)", "Freight Forwarding (Air)", "Cross-Border Trucking Service", "Customs Clearance Service", "Reverse Logistics Package", "Container Yard Storage", "Express Courier Service"],
    productCategories: ["Freight Services", "Warehousing", "Last-Mile Delivery", "Customs & Trade"],
    customerNamePool: ["Continental Retail Distribution", "Nexa E-Commerce Fulfillment", "Global Parts Import Co.", "FreshLine Cold Chain Client", "Metro Manufacturing Exports", "Harbor Trading Group", "QuickShip E-Retailers", "PanAsia Trading Co.", "Regional Auto Parts Distributor", "Coastal Import-Export Alliance", "BuildRight Materials Supply", "National Retail Fulfillment Network"],
    customerSegments: ["E-Commerce Client", "Manufacturing Exporter", "Retail Distributor", "Import-Export Trader"],
    supplierNamePool: ["FleetParts Trading Sdn Bhd", "PortServices Malaysia", "FuelLine Distribution", "PalletWorks Manufacturing", "WarehouseTech Equipment Co.", "TrackTech GPS Solutions", "CustomsBroker Partners"],
    supplierCategories: ["Fleet Maintenance", "Port & Terminal Services", "Fuel Supply", "Warehouse Equipment"],
    employeeDepartments: [
      { department: "Fleet Operations", titles: ["Fleet Manager", "Dispatch Coordinator", "Driver Supervisor"] },
      { department: "Warehouse", titles: ["Warehouse Manager", "Fulfillment Supervisor", "Inventory Controller"] },
      { department: "Customer Service", titles: ["Customer Service Manager", "Freight Coordinator"] },
      { department: "Finance", titles: ["Finance Manager", "Billing & Collections Executive"] },
      { department: "Trade & Customs", titles: ["Customs Compliance Officer", "Trade Documentation Executive"] },
    ],
    riskScenarios: [
      "Delivery delay reported on {product} for {customer}",
      "Fuel cost spike affecting margins on {product}",
      "{customer} invoice significantly overdue",
      "Warehouse capacity for {product} approaching full utilization",
      "Customs clearance delay affecting a cross-border shipment",
    ],
    opportunityScenarios: [
      "{customer} requesting expanded last-mile coverage",
      "New route opens faster transit for {product}",
      "{customer} proposing a long-term warehousing contract",
    ],
    milestoneScenarios: [
      "Completed highest-volume delivery week on record",
      "Onboarded {customer} as a new fulfillment client",
      "Achieved on-time delivery rate above 98% for the quarter",
    ],
    operationalScenarios: [
      "Fleet telematics upgrade completed across the delivery fleet",
      "New cross-dock facility brought online",
      "Route optimization software rolled out to dispatch",
    ],
    campaignChannels: ["Trade Publications", "Logistics Trade Shows", "Direct Outreach", "LinkedIn"],
    ticketSubjects: ["Shipment tracking inquiry", "Damaged cargo claim", "Delivery delay complaint", "Rate quote request"],
    documentTitles: [
      "Driver & Warehouse Staff Handbook 2026", "New Driver Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 Logistics Financial Report", "Outstanding Freight Invoice Register", "Freight Sales Playbook",
      "Monthly Shipment Pipeline Report", "Warehouse & Fleet Operations SOP", "Fleet & Warehouse Inventory Master List",
      "Carrier & Vendor Master Service Agreement", "Customs & Safety Compliance Checklist", "Staff Travel & Expense Policy",
      "Customer Support Response Guide", "Shipping FAQ Knowledge Base", "Brand & Marketing Guidelines",
      "Fleet & Warehouse IT Network Overview", "Board Report — Logistics Performance", "Operations Review Meeting Minutes",
      "New Dispatcher Training Manual", "Service Rate Catalogue 2026",
    ],
    documentDescriptions: [
      "Company-wide policies covering driver and warehouse conduct and safety standards.",
      "Step-by-step onboarding checklist for new drivers and warehouse staff.",
      "Annual leave entitlement, attendance tracking, and approval workflow.",
      "Consolidated shipment volumes, revenue, and cash flow for the quarter.",
      "Live register of issued freight invoices and their payment status.",
      "Freight sales process, rate quoting, and account management playbook.",
      "Snapshot of open shipment and contract discussions by stage.",
      "Standard procedures for receiving, cross-docking, and last-mile dispatch.",
      "Current fleet and warehouse capacity levels and utilization by site.",
      "Standard contract terms for approved carriers and equipment vendors.",
      "Checklist of customs and safety regulatory obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for staff travel.",
      "Approved response templates and escalation criteria for shipment complaints.",
      "Frequently asked shipping questions and approved answers by service line.",
      "Visual identity, tone of voice, and campaign approval process.",
      "Current fleet and warehouse network topology and access control map.",
      "Quarterly board briefing on logistics performance and shipment pipeline.",
      "Minutes from the monthly operations review meeting.",
      "Onboarding training manual for new dispatch coordinators.",
      "Current freight and warehousing service rate catalogue.",
    ],
    unitLabel: "shipments",
  },

  Construction: {
    industry: "Construction",
    tracksInventory: false,
    facilityLabel: "Site Office",
    companyNames: ["Bina Utama Construction Sdn Bhd", "Skyline Builders Group", "Cornerstone Infrastructure Sdn Bhd", "Pillar Construction & Engineering", "Horizon Development Group"],
    taglines: [
      "Building the region's next landmark.",
      "On budget, on schedule, built to last.",
      "Infrastructure that stands for generations.",
      "From blueprint to handover.",
    ],
    hqCities: [
      { city: "Kuala Lumpur", region: "Federal Territory" },
      { city: "Shah Alam", region: "Selangor" },
      { city: "Johor Bahru", region: "Johor" },
      { city: "Kota Kinabalu", region: "Sabah" },
    ],
    productNamePool: ["Residential Tower Project", "Commercial Office Fit-Out", "Highway Infrastructure Package", "Warehouse & Industrial Build", "Renovation & Retrofit Package", "Civil Earthworks Package", "Structural Steel Package", "MEP Installation Package", "Landscaping & External Works", "Bridge Construction Project", "School Building Project", "Facility Maintenance Contract"],
    productCategories: ["Residential Projects", "Commercial Projects", "Infrastructure Projects", "Maintenance Contracts"],
    customerNamePool: ["Skyline Property Developers", "National Infrastructure Authority", "Metro Township Development Corp.", "Coastal Resorts Development", "Greenfield Industrial Park Bhd", "CityLink Property Group", "Public Works Department", "Heritage Mall Developers", "Riverside Residences Sdn Bhd", "Enterprise Business Park Bhd", "Community Housing Trust", "National School Building Programme"],
    customerSegments: ["Private Developer", "Government Agency", "Industrial Client", "Institutional Client"],
    supplierNamePool: ["SteelFrame Structural Supply", "ReadyMix Concrete Sdn Bhd", "BuildMart Materials Trading", "ScaffoldPro Equipment Rental", "ElectroMEP Contractors", "GlassWorks Facade Supply", "HeavyLift Crane Rental"],
    supplierCategories: ["Structural Materials", "Concrete & Aggregates", "MEP Subcontractors", "Equipment Rental"],
    employeeDepartments: [
      { department: "Project Management", titles: ["Project Director", "Site Manager", "Project Engineer", "Quantity Surveyor"] },
      { department: "Site Operations", titles: ["Site Supervisor", "Safety Officer", "Foreman"] },
      { department: "Finance", titles: ["Finance Manager", "Contracts Accountant", "Billing Executive"] },
      { department: "Business Development", titles: ["Business Development Manager", "Tender Executive"] },
      { department: "Procurement", titles: ["Procurement Manager", "Subcontractor Coordinator"] },
    ],
    riskScenarios: [
      "{product} timeline slipping due to a subcontractor delay",
      "Material cost increase from {supplier} affecting project margin",
      "{customer} progress payment overdue",
      "Safety incident reported on a {product} site",
      "Weather delays affecting the {product} schedule",
    ],
    opportunityScenarios: [
      "{customer} inviting a tender for a follow-on project",
      "New government infrastructure programme opening bid opportunities",
      "{customer} requesting scope expansion on {product}",
    ],
    milestoneScenarios: [
      "Reached topping-out milestone on {product}",
      "Handed over {product} to {customer} ahead of schedule",
      "Won a new tender for a major infrastructure project",
    ],
    operationalScenarios: [
      "Site safety audit completed with no major findings",
      "New project scheduling software rolled out across sites",
      "Subcontractor performance review completed for the quarter",
    ],
    campaignChannels: ["Tender Portals", "Industry Associations", "Direct Client Relationships", "Trade Publications"],
    ticketSubjects: ["Defect liability period request", "Progress payment inquiry", "Variation order request", "Site safety concern"],
    documentTitles: [
      "Site Worker Handbook 2026", "New Site Staff Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 Project Financial Report", "Outstanding Progress Claim Register", "Tender & Sales Playbook",
      "Monthly Project Pipeline Report", "Site Operations & Safety SOP", "Materials & Equipment Inventory Master List",
      "Subcontractor Master Service Agreement", "Safety & Regulatory Compliance Checklist", "Site Travel & Expense Policy",
      "Client Support Response Guide", "Project FAQ Knowledge Base", "Brand & Proposal Guidelines",
      "Site IT & Project Systems Overview", "Board Report — Project Performance", "Project Steering Committee Minutes",
      "New Site Supervisor Training Manual", "Project Services Catalogue 2026",
    ],
    documentDescriptions: [
      "Company-wide policies covering site conduct, safety, and workplace standards.",
      "Step-by-step onboarding checklist for new site staff.",
      "Annual leave entitlement, attendance tracking, and approval workflow.",
      "Consolidated project revenue, cost, and cash flow for the quarter.",
      "Live register of submitted progress claims and their payment status.",
      "Tender preparation and client relationship playbook.",
      "Snapshot of open tenders and projects by stage.",
      "Standard procedures for site safety, material handling, and quality control.",
      "Current materials and equipment stock levels and reorder points by site.",
      "Standard contract terms for approved subcontractors and material suppliers.",
      "Checklist of safety and regulatory obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for site travel.",
      "Approved response templates and escalation criteria for client queries.",
      "Frequently asked client questions and approved answers by project type.",
      "Visual identity and tender proposal guidelines.",
      "Current site IT and project management systems topology and access map.",
      "Quarterly board briefing on project performance and tender pipeline.",
      "Minutes from the monthly project steering committee meeting.",
      "Onboarding and safety training manual for new site supervisors.",
      "Current project services catalogue with capability statements.",
    ],
    unitLabel: "projects",
  },

  Government: {
    industry: "Government",
    tracksInventory: false,
    facilityLabel: "Regional Office",
    companyNames: ["State Digital Services Agency", "National Public Works Department", "Metropolitan Municipal Council", "Regional Development Authority", "Public Services Delivery Agency"],
    taglines: [
      "Public service, modernized.",
      "Serving citizens with efficiency and transparency.",
      "Better government, one service at a time.",
      "Digital-first public administration.",
    ],
    hqCities: [
      { city: "Putrajaya", region: "Federal Territory" },
      { city: "Kuala Lumpur", region: "Federal Territory" },
      { city: "Kota Kinabalu", region: "Sabah" },
      { city: "Kuching", region: "Sarawak" },
    ],
    productNamePool: ["Citizen License Renewal Service", "Public Infrastructure Maintenance Programme", "Community Health Outreach Programme", "Business Permit Processing Service", "Public Housing Application Service", "Waste Management Programme", "Public Transport Subsidy Programme", "Digital ID Enrollment Service", "Social Welfare Assistance Programme", "Local Business Grant Programme", "Public Records Request Service", "Emergency Response Coordination Programme"],
    productCategories: ["Citizen Services", "Infrastructure Programmes", "Social Programmes", "Regulatory Services"],
    customerNamePool: ["District Municipal Office", "State Health Department", "National Housing Board", "Regional Transport Authority", "Community Development Council", "Local Business Chamber", "State Education Department", "Public Works Contractor Panel", "Citizen Advisory Committee", "State Revenue Board", "Emergency Services Coordination Unit", "National Statistics Department"],
    customerSegments: ["Inter-Agency Partner", "Citizen Service Recipient", "Contracted Vendor", "Community Organization"],
    supplierNamePool: ["GovTech Systems Integrator", "PublicWorks Materials Supply", "SecureCloud Government IT", "CitizenPortal Software Vendor", "InfraBuild Contractors Panel", "DataSecure Records Management", "FleetGov Vehicle Services"],
    supplierCategories: ["IT Systems Integration", "Infrastructure Contractors", "Records Management", "Fleet Services"],
    employeeDepartments: [
      { department: "Citizen Services", titles: ["Service Delivery Manager", "Citizen Services Officer", "Case Officer"] },
      { department: "Public Works", titles: ["Public Works Engineer", "Infrastructure Coordinator", "Field Inspector"] },
      { department: "Finance & Budget", titles: ["Budget Manager", "Finance Officer", "Grants Administrator"] },
      { department: "Policy & Compliance", titles: ["Policy Analyst", "Compliance Officer", "Audit Officer"] },
      { department: "IT & Digital Services", titles: ["Digital Services Manager", "Systems Administrator"] },
    ],
    riskScenarios: [
      "Processing backlog building on {product}",
      "Budget allocation for {product} at risk of underspend before year-end",
      "{customer} escalation on a delayed inter-agency request",
      "Vendor {supplier} reporting a project delay affecting {product}",
      "Public complaint volume rising on {product}",
    ],
    opportunityScenarios: [
      "Federal grant available to expand {product}",
      "{customer} proposing a joint programme on {product}",
      "Digital adoption rate for {product} ahead of target, freeing capacity for expansion",
    ],
    milestoneScenarios: [
      "Processed record volume of {product} applications this quarter",
      "Completed rollout of {product} to a new district",
      "Passed annual public accounts audit with no major findings",
    ],
    operationalScenarios: [
      "New case management system rolled out for {product}",
      "Public counter hours extended to reduce wait times",
      "Inter-agency data-sharing agreement finalized",
    ],
    campaignChannels: ["Public Notices", "Community Town Halls", "Government Portal", "Social Media"],
    ticketSubjects: ["Application status inquiry", "Service complaint", "Public records request", "Appeal submission"],
    documentTitles: [
      "Staff Handbook 2026", "New Officer Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 Budget Utilization Report", "Outstanding Grant Disbursement Register", "Inter-Agency Engagement Playbook",
      "Monthly Programme Pipeline Report", "Service Delivery Operations SOP", "Equipment & Records Inventory Master List",
      "Vendor Master Service Agreement", "Public Accountability Compliance Checklist", "Staff Travel & Expense Policy",
      "Citizen Support Response Guide", "Citizen Services FAQ Knowledge Base", "Public Communications Guidelines",
      "Government IT Network Overview", "Board Report — Programme Performance", "Steering Committee Meeting Minutes",
      "New Case Officer Training Manual", "Public Services Catalogue 2026",
    ],
    documentDescriptions: [
      "Agency-wide policies covering staff conduct, ethics, and workplace standards.",
      "Step-by-step onboarding checklist for new officers.",
      "Annual leave entitlement, attendance tracking, and approval workflow.",
      "Consolidated budget utilization and programme spend for the quarter.",
      "Live register of pending grant disbursements and their status.",
      "Inter-agency coordination and stakeholder engagement playbook.",
      "Snapshot of open programme initiatives by stage.",
      "Standard procedures for citizen service delivery and case handling.",
      "Current equipment and records stock levels and reorder points.",
      "Standard contract terms for approved vendors and contractors.",
      "Checklist of public accountability and audit obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for staff travel.",
      "Approved response templates and escalation criteria for citizen complaints.",
      "Frequently asked citizen questions and approved answers by service line.",
      "Public communications tone-of-voice and approval guidelines.",
      "Current government IT network topology and access control map.",
      "Quarterly board briefing on programme performance and delivery pipeline.",
      "Minutes from the monthly steering committee meeting.",
      "Onboarding training manual for new case officers.",
      "Current public services catalogue with eligibility criteria.",
    ],
    unitLabel: "cases",
  },

  Technology: {
    industry: "Technology",
    tracksInventory: false,
    facilityLabel: "Data Center",
    companyNames: ["Cyberia Software Solutions", "NexTech Cloud Systems", "Quantum Digital Sdn Bhd", "Vertex SaaS Group", "Bytewise Technologies"],
    taglines: [
      "Software that scales with you.",
      "Cloud-native, built for enterprise.",
      "Engineering the region's digital backbone.",
      "Ship faster, scale smarter.",
    ],
    hqCities: [
      { city: "Kuala Lumpur", region: "Federal Territory" },
      { city: "Cyberjaya", region: "Selangor" },
      { city: "Penang", region: "Penang" },
      { city: "Singapore", region: "Singapore" },
    ],
    productNamePool: ["Enterprise SaaS Platform License", "Cloud Infrastructure Hosting Plan", "API Integration Package", "Data Analytics Dashboard Suite", "Cybersecurity Monitoring Service", "Mobile App Development Package", "AI Automation Add-On", "Managed IT Support Plan", "Custom Software Development Contract", "DevOps Consulting Package", "Enterprise CRM Module", "Business Intelligence Suite"],
    productCategories: ["Software Licenses", "Cloud Services", "Professional Services", "Support Plans"],
    customerNamePool: ["Meridian Financial Group", "RetailChain Digital Transformation", "HealthNet Systems Integration", "LogiCorp Enterprise Client", "EduTech Learning Platform Client", "Manufacturing Analytics Client", "GovDigital Modernization Client", "FinServe Banking Client", "PropTech Solutions Client", "AgriTech Data Client", "InsureTech Platform Client", "Regional Telco Client"],
    customerSegments: ["Enterprise Account", "Mid-Market Account", "Startup Account", "Public Sector Account"],
    supplierNamePool: ["CloudCore Infrastructure Partners", "DevTools Licensing Sdn Bhd", "SecureStack Cybersecurity Vendor", "DataCenter Colocation Services", "APIGateway Platform Partner", "OpenSource Support Partners", "QASuite Testing Tools Vendor"],
    supplierCategories: ["Cloud Infrastructure", "Software Licensing", "Security Tools", "Development Tools"],
    employeeDepartments: [
      { department: "Engineering", titles: ["Engineering Manager", "Senior Software Engineer", "DevOps Engineer", "QA Engineer"] },
      { department: "Product", titles: ["Product Manager", "Product Designer", "Technical Writer"] },
      { department: "Sales", titles: ["Enterprise Account Executive", "Sales Development Representative", "Solutions Engineer"] },
      { department: "Customer Success", titles: ["Customer Success Manager", "Support Engineer"] },
      { department: "Finance", titles: ["Finance Manager", "Revenue Operations Analyst"] },
    ],
    riskScenarios: [
      "{customer} showing declining product usage — churn risk on {product}",
      "{customer} invoice overdue on {product} subscription",
      "Elevated error rate detected on {product} in production",
      "Key infrastructure vendor {supplier} reporting a service disruption",
      "Support ticket backlog rising for {product}",
    ],
    opportunityScenarios: [
      "{customer} requesting an upsell to a higher {product} tier",
      "New feature release driving strong trial-to-paid conversion on {product}",
      "{customer} open to becoming a reference customer",
    ],
    milestoneScenarios: [
      "Reached a new all-time-high monthly recurring revenue milestone",
      "Shipped a major {product} release with zero critical incidents",
      "Closed {customer} as a new enterprise logo",
    ],
    operationalScenarios: [
      "Infrastructure migration completed with no downtime",
      "New CI/CD pipeline rolled out across engineering",
      "Security audit completed with all findings remediated",
    ],
    campaignChannels: ["Product-Led Growth", "Webinars", "LinkedIn Ads", "Partner Co-Marketing"],
    ticketSubjects: ["API integration issue", "Billing discrepancy", "Feature request", "Production incident report"],
    documentTitles: [
      "Employee Handbook 2026", "New Hire Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 SaaS Financial Report", "Outstanding Subscription Invoice Register", "Enterprise Sales Playbook",
      "Monthly Pipeline & Renewal Report", "Engineering & Release Operations SOP", "License & Infrastructure Inventory Master List",
      "Vendor Master Service Agreement", "Security & Compliance Checklist", "Corporate Travel & Expense Policy",
      "Customer Support Response Guide", "Product FAQ Knowledge Base", "Brand & Product Marketing Guidelines",
      "Cloud Network Architecture Overview", "Board Report — SaaS Metrics", "Product Roadmap Meeting Minutes",
      "New Engineer Onboarding Training Manual", "Product & Pricing Catalogue 2026",
    ],
    documentDescriptions: [
      "Company-wide policies covering conduct, benefits, and workplace standards.",
      "Step-by-step onboarding checklist for new hires across departments.",
      "Annual leave entitlement, attendance tracking, and approval workflow.",
      "Consolidated recurring revenue, expenses, and cash flow for the quarter.",
      "Live register of issued subscription invoices and their payment status.",
      "Enterprise sales process, objection handling, and pricing guidance.",
      "Snapshot of open pipeline and upcoming renewals by stage and owner.",
      "Standard procedures for release management and production incident response.",
      "Current software license and infrastructure capacity inventory.",
      "Standard contract terms for approved infrastructure and tooling vendors.",
      "Checklist of security and compliance obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for business travel.",
      "Approved response templates and escalation criteria for support tickets.",
      "Frequently asked customer questions and approved answers by product line.",
      "Visual identity, tone of voice, and campaign approval process.",
      "Current cloud network topology, system ownership, and access control map.",
      "Quarterly board briefing on SaaS metrics and pipeline.",
      "Minutes from the monthly product roadmap review meeting.",
      "Onboarding training manual for new engineers.",
      "Current product and pricing catalogue by tier.",
    ],
    unitLabel: "licenses",
  },

  "Professional Services": {
    industry: "Professional Services",
    tracksInventory: false,
    facilityLabel: "Office Location",
    companyNames: ["Meridian Advisory Partners", "Cornerstone Consulting Group", "Apex Legal & Advisory Sdn Bhd", "Vantage Business Consultants", "Sterling Professional Group"],
    taglines: [
      "Advisory that moves your business forward.",
      "Expertise, delivered with precision.",
      "Trusted counsel for complex decisions.",
      "Consulting built on measurable outcomes.",
    ],
    hqCities: [
      { city: "Kuala Lumpur", region: "Federal Territory" },
      { city: "Petaling Jaya", region: "Selangor" },
      { city: "Singapore", region: "Singapore" },
      { city: "Penang", region: "Penang" },
    ],
    productNamePool: ["Strategy Advisory Engagement", "Tax & Compliance Retainer", "Audit & Assurance Engagement", "M&A Due Diligence Package", "HR & Organizational Consulting Package", "Legal Advisory Retainer", "Financial Restructuring Engagement", "Digital Transformation Advisory", "Risk & Compliance Assessment", "Executive Coaching Programme", "Market Entry Advisory Package", "Litigation Support Engagement"],
    productCategories: ["Advisory Engagements", "Retainer Services", "Assessment Projects", "Coaching Programmes"],
    customerNamePool: ["Meridian Manufacturing Group", "National Retail Holdings", "TechCorp Regional HQ", "Coastal Property Developers", "Family Office Investment Group", "Regional Bank Holdings", "HealthGroup Hospital Network", "Government Linked Corporation", "Logistics Conglomerate Bhd", "Consumer Goods Holding Co.", "Energy Sector Client", "Private Equity Portfolio Company"],
    customerSegments: ["Corporate Client", "Government-Linked Client", "Private Equity Client", "SME Client"],
    supplierNamePool: ["LegalTech Research Platform", "AuditTools Software Vendor", "DataRoom Secure Platform", "MarketIntel Research Partners", "ComplianceTech Vendor", "TrainingPartners Facilitation Co.", "OfficeServe Workplace Solutions"],
    supplierCategories: ["Research Platforms", "Compliance Software", "Facilitation Partners", "Workplace Services"],
    employeeDepartments: [
      { department: "Advisory", titles: ["Engagement Partner", "Senior Consultant", "Associate Consultant", "Analyst"] },
      { department: "Client Services", titles: ["Client Relationship Manager", "Engagement Coordinator"] },
      { department: "Finance", titles: ["Finance Manager", "Billing & Realization Analyst"] },
      { department: "Business Development", titles: ["Business Development Director", "Proposal Manager"] },
      { department: "Knowledge Management", titles: ["Knowledge Manager", "Research Analyst"] },
    ],
    riskScenarios: [
      "{customer} engagement showing scope creep against the {product} budget",
      "{customer} invoice overdue on {product} retainer",
      "Utilization rate for the advisory team below target this month",
      "Key subject-matter expert rolling off {product} mid-engagement",
      "{customer} escalation on a delayed deliverable",
    ],
    opportunityScenarios: [
      "{customer} requesting an extension into a follow-on {product}",
      "New regulatory change creating demand for {product}",
      "{customer} open to a multi-year retainer on {product}",
    ],
    milestoneScenarios: [
      "Closed {customer} as a new marquee client",
      "Delivered {product} ahead of the engagement timeline",
      "Reached record quarterly billable utilization",
    ],
    operationalScenarios: [
      "New engagement management system rolled out firm-wide",
      "Knowledge base refreshed with the latest regulatory guidance",
      "Staffing plan finalized for next quarter's engagements",
    ],
    campaignChannels: ["Thought Leadership Content", "Industry Conferences", "Referral Network", "LinkedIn"],
    ticketSubjects: ["Engagement scope clarification", "Invoice/billing dispute", "Deliverable timeline inquiry", "Data request follow-up"],
    documentTitles: [
      "Employee Handbook 2026", "New Consultant Onboarding SOP", "Leave & Attendance Policy",
      "Q1 2026 Firm Financial Report", "Outstanding Client Invoice Register", "Business Development Playbook",
      "Monthly Engagement Pipeline Report", "Engagement Delivery Operations SOP", "Knowledge Asset Inventory Master List",
      "Vendor Master Service Agreement", "Professional Standards Compliance Checklist", "Consultant Travel & Expense Policy",
      "Client Support Response Guide", "Client FAQ Knowledge Base", "Brand & Proposal Guidelines",
      "Firm IT & Data Room Overview", "Board Report — Firm Performance", "Partner Meeting Minutes",
      "New Analyst Training Manual", "Services & Rate Card Catalogue 2026",
    ],
    documentDescriptions: [
      "Firm-wide policies covering conduct, ethics, and workplace standards.",
      "Step-by-step onboarding checklist for new consultants.",
      "Annual leave entitlement, attendance tracking, and approval workflow.",
      "Consolidated firm revenue, realization, and cash flow for the quarter.",
      "Live register of issued client invoices and their payment status.",
      "Business development process and proposal playbook.",
      "Snapshot of open engagements and proposals by stage.",
      "Standard procedures for engagement delivery, quality review, and sign-off.",
      "Current knowledge asset and research library inventory.",
      "Standard contract terms for approved research and technology vendors.",
      "Checklist of professional standards and independence obligations reviewed each quarter.",
      "Approval thresholds and reimbursement process for consultant travel.",
      "Approved response templates and escalation criteria for client queries.",
      "Frequently asked client questions and approved answers by service line.",
      "Visual identity and proposal/pitch deck guidelines.",
      "Current firm IT and secure data room topology and access map.",
      "Quarterly board briefing on firm performance and engagement pipeline.",
      "Minutes from the monthly partner meeting.",
      "Onboarding training manual for new analysts.",
      "Current services and rate card catalogue by practice area.",
    ],
    unitLabel: "engagements",
  },
};

export const INDUSTRIES = Object.keys(INDUSTRY_TEMPLATES) as Industry[];
